    electronic_settings = [prec_level, algo, encut , nelm,nelmin, ediff, sigma,   lasph, lreal, addgrid, bmaxmix, bmix]
    ionic_settings = [ediff, nsw, ibrion ,isif, isym, nblock, kblock]
    magnetic_settings = [ispin, magmom, nupdown, saxis, lsorbit,noncollinear]
    hubbard_settings = [ldau, ldatype, ldaul, dlauu, ldauj, lmaxmix]
    hybrid_settings = [lhfcalc, precfock, nkred, algo, time, hflmax, hfscreen, aexx]
    rho_decomp = [lpard, eint, dbmod, kpuse, iband]
